name: github-trigger

on:
  workflow_call:
    inputs:
      PRIMUS_REF:
        description: 'The primus ref to checkout.'
        required: true
        default: 'main'
        type: string
      GITHUB_SILENT:
        description: 'Whether to run the Primus GitHub operation silently.'
        type: boolean
      GITHUB_REPOSITORY_NAME:
        description: 'The name of the repository with the GitHub workflow to trigger.'
        required: true
        type: string
      GITHUB_EVENT_NAME:
        description: 'The name of the event to trigger.'
        required: true
        type: string
      GITHUB_EVENT_PAYLOAD:
        description: 'The payload of the event to trigger.'
        default: '{}'
        type: string

defaults:
  run:
    shell: bash

env:
  PRIMUS_HOME: .primus
  MAKE: make --no-print-directory --makefile=.primus/src/make/main.mk

jobs:
  signoz:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - id: token
        name: github-token-gen
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PRIMUS_APP_ID }}
          private-key: ${{ secrets.PRIMUS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: primus-checkout
        uses: actions/checkout@v4
        with:
          repository: signoz/primus
          ref: ${{ inputs.PRIMUS_REF }}
          path: .primus
          token: ${{ steps.token.outputs.token }}
      - name: info
        run: |
          $MAKE info
      - name: trigger
        env:
          GH_EVENT_PAYLOAD: ${{ inputs.GITHUB_EVENT_PAYLOAD }}
        run: |
          GH_EVENT_PAYLOAD=$(echo "${GH_EVENT_PAYLOAD}" | jq -c . | jq -rR .)
          ADDITIONAL_ARGS=""
          if [ "${{ inputs.GITHUB_SILENT }}" = "true" ]; then
            ADDITIONAL_ARGS="-s"
          fi
          $MAKE github-event-trigger-workflow \
            GITHUB_ARGS="-t ${{ steps.token.outputs.token }} \
              -r ${{ inputs.GITHUB_REPOSITORY_NAME }} \
              -e ${{ inputs.GITHUB_EVENT_NAME }} \
              -p '${GH_EVENT_PAYLOAD}' \
              ${ADDITIONAL_ARGS}"
