name: js-build
on:
  workflow_call:
    inputs:
      PRIMUS_REF:
        description: 'The primus ref to checkout.'
        required: true
        default: 'main'
        type: string
      JS_SRC:
        description: 'The path to the source directory. If not provided, the defaults to the root of the repository.'
        default: '.'
        type: string
      JS_INPUT_ARTIFACT_CACHE_KEY:
        description: 'The key to cache the input artifacts.'
        type: string
      JS_INPUT_ARTIFACT_PATH:
        description: 'The path to the input artifacts.'
        type: string
      JS_OUTPUT_ARTIFACT_CACHE_KEY:
        description: 'The key to cache the output artifacts.'
        type: string
      JS_OUTPUT_ARTIFACT_PATH:
        description: 'The path to the output artifacts.'
        type: string
      DOCKER_BUILD:
        description: 'Whether to build the docker image or not.'
        default: true
        type: boolean
      DOCKER_BASE_IMAGES:
        description: 'List of docker base images in json.'
        type: string
      DOCKER_DOCKERFILE_PATH:
        description: 'Path to dockerfile.'
        type: string
      DOCKER_MANIFEST:
        description: 'Whether to push the docker image or not.'
        required: true
        type: boolean
      DOCKER_ARCHS:
        description: 'List of architectures to build the docker image.'
        default: 'amd64 arm64'
        type: string
      DOCKER_PROVIDERS:
        description: 'The docker providers to use, separated by spaces. (dockerhub gcp aws)'
        default: 'gcp'
        type: string
defaults:
  run:
    shell: bash

env:
  PRIMUS_HOME: .primus
  MAKE: make --no-print-directory --makefile=.primus/src/make/main.mk
  
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_type == 'tag' && 'production' || github.ref_name == 'main' && 'staging' || 'review' }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - id: token
        name: github-token-gen
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PRIMUS_APP_ID }}
          private-key: ${{ secrets.PRIMUS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: primus-checkout
        uses: actions/checkout@v4
        with:
          repository: signoz/primus
          ref: ${{ inputs.PRIMUS_REF }}
          path: .primus
          token: ${{ steps.token.outputs.token }}
      - name: qemu-install
        uses: docker/setup-qemu-action@v3
      - name: info
        run: |
          $MAKE info
      - name: input-artifacts-cache
        if: ${{ inputs.JS_INPUT_ARTIFACT_CACHE_KEY }}
        uses: actions/cache@v4
        with:
          key: ${{ inputs.JS_INPUT_ARTIFACT_CACHE_KEY }}
          path: ${{ inputs.JS_INPUT_ARTIFACT_PATH }}
      - name: build-variables
        run: |
          echo "JS_SRC=${{ inputs.JS_SRC }}" >> $GITHUB_ENV
          echo "DOCKER_ARCHS=${{ inputs.DOCKER_ARCHS }}" >> $GITHUB_ENV
          echo 'DOCKER_BASE_IMAGES=${{ inputs.DOCKER_BASE_IMAGES }}' >> $GITHUB_ENV
          echo "DOCKER_DOCKERFILE_PATH=${{ inputs.DOCKER_DOCKERFILE_PATH }}" >> $GITHUB_ENV
          echo "DOCKER_MANIFEST=${{ inputs.DOCKER_MANIFEST }}" >> $GITHUB_ENV
          echo "DOCKER_PROVIDERS=${{ inputs.DOCKER_PROVIDERS }}" >> $GITHUB_ENV
      - name: js-build
        run: |
          $MAKE js-build
      - name: output-artifacts-cache
        if: ${{ inputs.JS_OUTPUT_ARTIFACT_CACHE_KEY }}
        uses: actions/cache@v4
        with:
          key: ${{ inputs.JS_OUTPUT_ARTIFACT_CACHE_KEY }}
          path: ${{ inputs.JS_OUTPUT_ARTIFACT_PATH }}
      - name: docker-build
        if: ${{ inputs.DOCKER_BUILD }}
        run: |
          $MAKE docker-build
      - name: docker-auth
        if: ${{ inputs.DOCKER_MANIFEST && contains(inputs.DOCKER_PROVIDERS, 'dockerhub') }}
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" >> $GITHUB_ENV
      - name: docker-manifest
        if: ${{ inputs.DOCKER_MANIFEST }}
        run: |
          $MAKE docker-push docker-manifest
