name: py-test
on:
  workflow_call:
    inputs:
      PRIMUS_REF:
        description: 'The primus ref to checkout.'
        required: true
        default: 'main'
        type: string
      PYTHON_VERSION:
        description: 'The python version to use.'
        required: false
        default: '3.12'
        type: string
      PY_SRC:
        description: 'The directory path containing the py source code.'
        required: true
        type: string
      PY_PKG_MANAGER:
        description: 'The python package manager to use.'
        required: false
        default: 'uv'
        type: string

defaults:
  run:
    shell: bash

env:
  PRIMUS_HOME: .primus
  MAKE: make --no-print-directory --makefile=.primus/src/make/main.mk

jobs:
  py:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      - id: token
        name: github-token-gen
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PRIMUS_APP_ID }}
          private-key: ${{ secrets.PRIMUS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: primus-checkout
        uses: actions/checkout@v4
        with:
          repository: signoz/primus
          ref: ${{ inputs.PRIMUS_REF }}
          path: .primus
          token: ${{ steps.token.outputs.token }}
      - name: python-install
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}
      - name: uv-install
        if: ${{ inputs.PY_PKG_MANAGER == 'uv' }}
        uses: astral-sh/setup-uv@v6
      - name: info
        run: |
          $MAKE info
      - name: py-test
        run: |
          $MAKE py-test SRC="$(pwd)/${{ inputs.PY_SRC }}"
        env:
          PY_PKG_MANAGER: ${{ inputs.PY_PKG_MANAGER }}
